  services:
    web:
      build: .
      env_file:
        - .env
      ports:
        - "8000:8000"
      depends_on:
        redis:
            condition: service_healthy
        db:
          condition: service_healthy
      volumes:
        - .:/app
      networks:
        - secrets-network

    db:
      image: postgres:16
      container_name: secrets-db
      environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      healthcheck:
        test: pg_isready -d ${DB_NAME} -U ${DB_USER}
        interval: 10s
        timeout: 5s
        retries: 5
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
      networks:
        - secrets-network

    redis:
      image: redis:7.4.2
      ports:
        - "6379:6379"
      command: redis-server --bind 0.0.0.0
      healthcheck:
        test: [ "CMD", "redis-cli", "ping" ]
        interval: 10s
        timeout: 5s
        retries: 5
      networks:
        - secrets-network

  volumes:
    postgres_data:

  networks:
    secrets-network:
      driver: bridge